#%RAML 1.0 NamedExample
incident:
    id: 70fbf07b2fb6111025bed3f62799b6ae
    number: INC0000007
    opened_at: 2015-08-12 16:08:24
    caller_id: Joe Employee
    category: Database
    subcategory: Oracle
    state: On Hold
    impact: 1
    urgency: 1
    short_description: Need access to sales DB for the West
    description: I have to analyze all US data in the SFA system, but am unable to get to see the data from the west coast.